export const objectInfo = [
    {   objectWidth: 36,
        objectHeight: 38,
        objectRow: 1405,
        objectCol: 290,
    },
    {   objectWidth: 54,
        objectHeight: 26,
        objectRow: 780,
        objectCol: 820,
    },
    {   objectWidth: 54,
        objectHeight: 26,
        objectRow: 1800,
        objectCol: 780,
    },
    {   objectWidth: 54,
        objectHeight: 26,
        objectRow: 750,
        objectCol: 750,
    },
    {   objectWidth: 54,
        objectHeight: 26,
        objectRow: 1000,
        objectCol: 1000,
    },
    {   objectWidth: 54,
        objectHeight: 26,
        objectRow: 500,
        objectCol: 500,
    }


]